# Setup
title:               Ways of thought
tagline:             ''
description:         'A Critical thought a day keeps the assumptions away'
url:                 https://Ol-401.github.io
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              Oliver Claxton
  url:               ""
  email:             oliver.claxton05@gmail.com



# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

Themes:
  - title: Themes
    url: /Themes/2023-12-22-Themes.md