# Setup
title:               A Critical Thought
tagline:             ''
description:         'A Critical thought a day keeps the assumptions away'
url:                 https://Ol-401.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Oliver Claxton
  url:               ""
  email:             oliver.claxton05@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
